version: '2'
services:
  blog:
    image: mrsu/blog
    restart: always
    environment:
      - DOMAIN_NAME=mrsu.me
      - USER_ID=1001
      - USER_GID=1001
      - WEB_HOME=/home/admin/web/mrsu.me
      - PROJECT_NAME=mrsu
    volumes:
      - '/home/admin:/home/admin'
    ports:
      - '8900:80'
