version: '2'
services:
  blog:
    image: mrsu/blog
    restart: always
    environment:
      - DOMAIN_NAME=mrsu.me
      - USER_ID=1001
      - USER_GID=1001
      - WEB_HOME=/home/mrsu/work/test/mrsu.me
    volumes:
      - '/home/mrsu:/home/mrsu'
    ports:
      - '8900:80'
